#!/bin/bash

# Handy ls aliases.
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alF'

# Text editors.
alias vim='vim -O'
alias vi='vim'
alias emacs='emacs -nw'

# File utilities.
alias rm='rm -i'
alias opn='xdg-open 2> /dev/null'
alias texclean='rm -f *.aux *.log *.bbl *.blg'

# SSH/screen shortcuts.
alias skym='ssh skym -t "screen -UxRR"'
