#!/bin/bash

if [ $OSNAME == 'darwin' ]; then
  source $(brew --prefix)/opt/chruby/share/chruby/chruby.sh
  source $(brew --prefix)/opt/chruby/share/chruby/auto.sh
  chruby ruby-3.2.2

  export GEM_HOME="$HOME/.gems"
  PATH="$HOME/.gems/bin:$PATH"
elif [[ $OSNAME == linux* ]]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
fi
