#
# nginx conf for MediaWiki, with short URL rewriting
#

location / {
  try_files $uri $uri/ @mediawiki;
}
location @mediawiki {
  rewrite ^/(.*)$ /index.php?title=$1&$args;
}

#location /wiki/ {
#  rewrite ^/wiki/(?<pagename>.*)$ /index.php;
#}

#------------------------------------------------------------------------------

location ~ ^/(COPYING|CREDITS) {
  default_type text/plain;
}
location = /favicon.ico {
  add_header Cache-Control "public";
  expires max;
}
location = /robots.txt { }

# Hide other toplevel files and all dotfiles.
location ~ ^/[^/]+\.[^/]$ {
  log_not_found off;
  deny all;
}
location ~ /\. {
  access_log off;
  log_not_found off;
  deny all;
}

#------------------------------------------------------------------------------

# Point unbound images and static resource paths to index.php.
location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico)$ {
  try_files $uri /index.php;
  expires max;
  log_not_found off;
}

location ^~ ^/images/ {
  add_header X-Content-Type-Options "nosniff";
  # Force suspicious image files to a harmless MIME type.
  types { text/plain html htm shtml phtml php; }
  try_files $uri /index.php;
}

location ~ ^/resources/(assets|lib|src) {
  add_header Cache-Control "public";
  expires 7d;
  try_files $uri =404;
}
location ~ ^/skins/.+\.(css|js|gif|jpg|jpeg|png|svg|wasm|ttf|woff|woff2)$ {
  add_header Cache-Control "public";
  expires 7d;
  try_files $uri =404;
}

#------------------------------------------------------------------------------

# Deny all access to cache and deleted images.
location ^~ ^/cache/ { deny all; }
location ^~ ^/images/deleted/ { deny all; }

# Prohibit access to internals.
location ^~ ^/bin/ { internal; }
location ^~ ^/docs/ { internal; }
location ^~ ^/extensions/ { internal; }
location ^~ ^/includes/ { internal; }
location ^~ ^/languages/ { internal; }
location ^~ ^/maintenance/ { internal; }
location ^~ ^/resources/ { internal; }
location ^~ ^/serialized/ { internal; }
location ^~ ^/tests/ { internal; }
location ^~ ^/vendor/ { internal; }
location ^~ ^/mw-config/ { internal; }
